### ISSUE TITLE
Recalibration Dataset 

### ISSUE THREAD

**Issue by cstamatiadis** [ermongroup/CalibratedModelBasedRL#1]
I have a question regarding the following line:
https://github.com/ermongroup/CalibratedModelBasedRL/blob/9cead70bc1c632bf2bd7aba746b3d58bf14f65c5/dmbrl/modeling/models/BNN.py#L282
shouldn't it be `cdf_pred <= p` instead? I was going through a previous [paper](https://arxiv.org/pdf/1807.00263.pdf) of your group and the target values for the recalibration model seems to be computed with a non-strict inequality. Also in successive parts of the code (e.g. when computing the calibration plots) you always use strict inequalities. If this is meant to be like that, could please elaborate on it?

**Comment by malik-ali** [comment]
I think it doesn't matter. If you look at the definition of calibration, it says a predictive cdf F is calibrated if, for all p in [0, 1]:

`P(S <= F^{-1}(p)) = p`.

Since this is a probability about continuous values, a strict vs non-strict inequality shouldn't matter. In other words, for a continuous random variable X, `P(X <= a) = P(X < a)`. Therefore, it should be true that `P(S <= F^{-1}(p)) = P(S < F^{-1}(p))`.

[Strict Inequality Using CDF](https://math.stackexchange.com/questions/781179/strict-inequality-using-cdf)

**Comment by cstamatiadis** [comment]
You're right! The set I was using to check it wasn't ideal. But by changing it, things turn out the way they should. Thanks :)
